### ISSUE TITLE
Remove ineffectual attachment size constraints

### ISSUE THREAD

**Issue by OldSneerJaw** [OldSneerJaw/couchster#22]
# Task

## Description

Due to a performance optimization in CouchDB, it is not possible to determine the size of a new file attachment at the time that the validation function is run. This results in the attachment size constraints (i.e. `attachmentConstraints.maximumIndividualSize`, `attachmentConstraints.maximumTotalSize` and the `attachmentReference` validation type's `maximumSize`) being largely ineffectual. The documentation for the constraints was already removed in pull request #21. Remove the constraints altogether from the codebase since they cannot be enforced reliably.

More info about the underlying issue can be found at https://github.com/apache/couchdb/issues/1320.

**Comment by dkichler** [comment]
Addressed by #21 and #26
